{
  "metadata": "sequencing_experiment.json",
  "files": [],
  "validation": {
    "status": "INVALID",
    "checks": [
      {
        "checker": "c110_rg_id_uniqueness",
        "status": "VALID",
        "message": "Read group ID uniqueness check status: VALID"
      },
      {
        "checker": "c120_permissible_char_in_rg_id",
        "status": "VALID",
        "message": "Read group ID permissible character check status: VALID"
      },
      {
        "checker": "c130_one_sample",
        "status": "INVALID",
        "message": "'samples' section must contain exactly one sample in metadata, 2 found"
      },
      {
        "checker": "c140_platform_unit_uniqueness",
        "status": "VALID",
        "message": "Platform unit uniqueness check status: VALID"
      },
      {
        "checker": "c150_rg_count_match",
        "status": "INVALID",
        "message": "The total number of read groups in 'read_groups' section is 3. It does NOT match the number specified in read_group_count: 4."
      },
      {
        "checker": "c160_file_r1_r2_check",
        "status": "INVALID",
        "message": "File(s) specified in 'file_r1' or 'file_r2' missed in 'files' section of the metadata JSON: test_rg_4.bam"
      },
      {
        "checker": "c170_fq_uniqueness_in_rgs",
        "status": "VALID",
        "message": "FASTQ uniqueness in read groups check status: VALID"
      },
      {
        "checker": "c180_file_uniqueness",
        "status": "VALID",
        "message": "Files uniqueness check in files section status: VALID"
      },
      {
        "checker": "c200_rg_id_in_bam_uniqueness",
        "status": "VALID",
        "message": "'read_group_id_in_bam' uniqueness check status: VALID"
      },
      {
        "checker": "c210_no_path_in_filename",
        "status": "INVALID",
        "message": "'fileName' must NOT contain path in the 'files' section of the metadata, offending name(s): 'seq/test_rg_3.bam'"
      },
      {
        "checker": "c220_no_rg_id_in_bam_for_fq",
        "status": "VALID",
        "message": "'read_group_id_in_bam' not populated for FASTQ check: VALID"
      },
      {
        "checker": "c605_all_files_accessible",
        "status": "INVALID",
        "message": "Files specified in metadata, but missed in submission directory: 'seq/test_rg_3.bam, test_rg_3.bam'"
      },
      {
        "checker": "c607_coverage_estimate",
        "status": "UNKNOWN",
        "message": "An exception occurred during the execution of this checker. This is likely due to problem(s) identified by earlier check(s), please fix reported problem and then run the validation again. More information of the exception can be found in the latest log file under: no_files.WXS/logs/"
      },
      {
        "checker": "c610_rg_id_in_bam",
        "status": "UNKNOWN",
        "message": "An exception occurred during the execution of this checker. This is likely due to problem(s) identified by earlier check(s), please fix reported problem and then run the validation again. More information of the exception can be found in the latest log file under: no_files.WXS/logs/"
      },
      {
        "checker": "c630_rg_id_in_bam_match",
        "status": "UNKNOWN",
        "message": "An exception occurred during the execution of this checker. This is likely due to problem(s) identified by earlier check(s), please fix reported problem and then run the validation again. More information of the exception can be found in the latest log file under: no_files.WXS/logs/"
      },
      {
        "checker": "c640_one_sm_in_bam_header",
        "status": "UNKNOWN",
        "message": "An exception occurred during the execution of this checker. This is likely due to problem(s) identified by earlier check(s), please fix reported problem and then run the validation again. More information of the exception can be found in the latest log file under: no_files.WXS/logs/"
      },
      {
        "checker": "c650_sm_in_bam_matches_metadata",
        "status": "UNKNOWN",
        "message": "An exception occurred during the execution of this checker. This is likely due to problem(s) identified by earlier check(s), please fix reported problem and then run the validation again. More information of the exception can be found in the latest log file under: no_files.WXS/logs/"
      },
      {
        "checker": "c660_metadata_in_bam_rg_header",
        "status": "UNKNOWN",
        "message": "Not all dependent checks are in VALID status: c160_file_r1_r2_check: INVALID, c605_all_files_accessible: INVALID, c610_rg_id_in_bam: UNKNOWN. Please fix reported problem and then run the validation again."
      }
    ]
  }
}
